# Generated by Django 3.0.6 on 2020-07-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
