# Generated by Django 3.0.6 on 2020-07-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200715_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_submitted',
        ),
    ]
