# Generated by Django 3.0.6 on 2020-07-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_order_order_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_Email',
            field=models.EmailField(default='fake@email.com', max_length=254),
            preserve_default=False,
        ),
    ]
