# Generated by Django 3.0.6 on 2020-07-19 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_order_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_Phone',
        ),
    ]
