# Generated by Django 3.0.6 on 2020-07-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_order_is_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items_json',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
