# Generated by Django 3.0.6 on 2020-07-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20200723_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_ready',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items_json',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
