# Generated by Django 3.0.6 on 2020-07-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_remove_item_instance_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
            preserve_default=False,
        ),
    ]
