# Generated by Django 3.0.6 on 2020-07-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_auto_20200727_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_code',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
